<a href="https://colab.research.google.com/github/agreco92/Tutorials/blob/main/Tutorial_pt1_1605.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 0. Hello, World!

Hi, I'm a Google Colab notebook that will introduce you to some basic concepts in Python! 

Let's start by printing something to get you familiar with the environment using `print()`:

In [10]:
print("Hello, World!")

## 1. Variables and values

While programming, you will often need to give a name to things that you don't know yet. 

For example, a program that prints the name and the age of the user will need to store the input in a *box* labelled *User_name*. 

In this example, `name` is the **variable** and `Alice` will be its **value**.

In [11]:
name = "Alice"
age = 15
print(name, "is", age, "years old.")

Each variable has a **type**, that indicates what kind of value is in the variable. You can discover the type of an object using `type()`

In [12]:
type(name)

#### [practice] Not my type

Print a message that shows the type of the `age` variable

In [ ]:
# your code here!

### Functions

You've seen that many instructions in Python contain **parentheses** `()`. What do they mean?
They are used to use **functions**. Functions contain one or more line of code that is run each time that function is called. 

The functions we used so far are `print()` and `type()`. 

Later in one of these tutorials we will learn how to make our own function.

### Lists

Sometimes you need to store many things in the same box. **Lists** can do that!

In [14]:
colors = ['red', 'blue', 'green','yellow']
print(len(colors))
print(type(colors))

What if you just need one element of a list? You can access single slots of the list using the `list[number]` syntax. 

In [ ]:
print(colors[1]) # why is it not red? Because Python starts counting from zero!


#### [practice] Last but not least

Print only the last element of the list of colours **without using numbers explicitly**.

*Tip*: Use one of the functions in the previous cell, and remember that counting starts from 0 in Python!

In [ ]:
# your code here!

yellow


## 2. Decisions, decisions: if statement and for loop

### If statement

An `if` statement checks a condition: if the condition is true, Python executes the block of code under it; if the condition is false, the program can execute a different block of code under an `else` statement.

In [16]:
# test if a number is greater then a threshold
number = 27
threshold = 100

if number < threshold:
  print(number, " is greater than ", threshold)
else:
  print(number, " is smaller than ", threshold)

print("\n Have a good day, bye!")

Did you see that? The statements below the if statement are *shifted* by some blank spaces. 

This structure is called **indentation** and is necessary so that Python understands when the `if` and `else` statements are over.

#### [practice] ...Manners!
Try to move the goodbye message inside the `else` statement using the `Tab` key and try different numbers. What happens?

In [ ]:
# your code here!

190  is smaller than  100

 Have a good day, bye!


### For loop

Sometimes you need to do the same thing multiple times. Luckily, the `for` loop automatically repeats the same action throughout a list 


In [13]:
for color in colors:
    print(color)

red
blue
green
yellow


If you need to explicitly access the slot number in a for loop, you can use the `range` function!

In [ ]:
# The range() function can take up to three arguments:
# range(stop) - counts from 0 to stop-1
# range(start, stop) - counts from start to stop-1
# range(start, stop, step) - counts from start to stop-1 with given step size

for i in range(0, len(colors),1): 
    print(colors[i])

#### [practice] Top 5

1. Create a list of your top 5 movies (or songs, or videogames) and print them sequentially. E.g.: **"Movie nr 5 in my favourite list is Barbie"**
<br>*Tip*: Use `range` and a for loop to access specific positions in the list

2. Movie ranked 0 sounds weird -  Try to make the list a bit more readable, from 1 to 5
   
3. Everybody likes suspance! -  Print the list from worst to best (without changing the list!) <br> *Tip*: You can change the step in the `range` function to -1 to iterate backwards!

In [ ]:
# your code here!

#### [practice] Max and Min

Use a combination of the for loop and the if construct to detect the highest and lowest number in a given list.

In [ ]:
# your code here!

The maximum number in the list is: 99
The minimum number in the list is: 3


#### [practice] = or ==?

Given a list of numbers and a target, write a for loop that checks if each number in the list matches the target. If this happens, it prints the index of the match. 


In [ ]:
# your code here!

## 3. Higher dimensions: introduction to numpy arrays


Arrays are special variables that are ideal to deal with complex data. To create and manipulate arrays, we will use the `numpy` library, that contains pre-defined functions and data types. Let's start by creating a simple array:

### One-dimensional arrays

In [15]:
import numpy as np # numpy is a library: contains functions and data types that are useful for scientific computing.
array = np.array([1,2,3])
print(array)

[1 2 3]


In [16]:
print(array.shape, array.size, array.dtype)

(3,) 3 int64


### Two-dimensional arrays (matrices)

In [17]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
print(matrix.shape, matrix.size, matrix.dtype)

(3, 3) 9 int64


Matrices do not have just one index, but two: One for rows, and one for columns!


In [19]:
print("First row:", matrix[0,:])
print("First column:", matrix[:,0])
print("First element of first row:", matrix[0][0])
print("Element in second row, third column:", matrix[1][2])


First row: [1 2 3]
First column: [1 4 7]
First element of first row: 1
Element in second row, third column: 6


#### [practice] Loop the Matrix
1. Create a matrix with 3 rows and 4 columns
2. Create a `for`loop that prints each row of the matrix<br>*Tip*:The total number of rows in the matrix can be accessed using `matrix.shape[0]`
3. Create a `for` loop that prints each column of the matrix
4. Create a nested loop (two `for` loops inside each other) that prints each element of the matrix

In [ ]:
# your code here!

Row 0 : [1 2 3 4]
Row 1 : [5 6 7 8]
Row 2 : [ 7  8  9 10]
Column 0 : [1 5 7]
Column 1 : [2 6 8]
Column 2 : [3 7 9]
Column 3 : [ 4  8 10]
Element in row 0 and column 0 : 1
Element in row 0 and column 1 : 2
Element in row 0 and column 2 : 3
Element in row 0 and column 3 : 4
Element in row 1 and column 0 : 5
Element in row 1 and column 1 : 6
Element in row 1 and column 2 : 7
Element in row 1 and column 3 : 8
Element in row 2 and column 0 : 7
Element in row 2 and column 1 : 8
Element in row 2 and column 2 : 9
Element in row 2 and column 3 : 10


### Matrix operations


You can add and subtract arrays of the same size:

In [26]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 3], [0, 1]])

# Matrix Addition
C = A + B
print("Added Matrices:\n", C)

# Matrix Subtraction
D = A - B
print("Subtracted Matrices:\n", D)


There's several ways to multiply matrices. For example, one can multiply each element of a matrix for the same number (called *scalar* in this context), or multiply two matrices of the same size element by element (Element-wise product, or *Hadamard* product)

In [27]:
# Scalar Multiplication
scalar = 3
E = scalar * A
print("Scalar Multiplied Matrix:\n", E)

# Element-wise Multiplication
C = A * B  # Using the '*' operator for element-wise multiplication
print("Element-wise multiplied Matrix C:\n", C)

#### [practice] The Hole

Create a matrix of random numbers that contains a "hole" in the middle made of zeroes. 

*Tip*: Useful functions: `np.ones()`, `np.random.randn()`, `np.zeroes()` 


In [ ]:
# your code here!

Original Random Matrix:
 [[ 1.29471023  0.62981611  0.26978452  0.04884361 -0.5444123 ]
 [-0.51884199  0.11022159 -0.08493667  1.65139458  1.51110577]
 [ 0.73255933 -0.0598596  -1.24386562 -0.79538455  0.73039237]
 [-0.67413114  0.28005836 -1.16437781  1.62905026  0.22093345]
 [-0.45919505  0.50988807 -0.00668934 -0.33793285  1.04030081]]
Mask Matrix:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
Random Matrix with a 3x3 Hole:
 [[ 1.29471023  0.62981611  0.26978452  0.04884361 -0.5444123 ]
 [-0.51884199  0.         -0.          0.          1.51110577]
 [ 0.73255933 -0.         -0.         -0.          0.73039237]
 [-0.67413114  0.         -0.          0.          0.22093345]
 [-0.45919505  0.50988807 -0.00668934 -0.33793285  1.04030081]]
