<a href="https://colab.research.google.com/github/agreco92/Tutorials/blob/main/Tutorial_pt1_1605.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 0. Hello, World!

Hi, I'm a Google Colab notebook that will introduce you to some basic concepts in Python! 

Let's start by printing something to get you familiar with the environment using `print()`:

In [10]:
print("Hello, World!")

Hello, World!


## 1. Variables and values

While programming, you will often need to give a name to things that you don't know yet. 

For example, a program that prints the name and the age of the user will need to store the input in a *box* labelled *User_name*. 

In this example, `name` is the **variable** and `Alice` will be its **value**.

In [11]:
name = "Alice"
age = 15
print(name, "is", age, "years old.")

Alice is 15 years old.


Each variable has a **type**, that indicates what kind of value is in the variable. You can discover the type of an object using `type()`

In [12]:
type(name)

str

#### [exercise] Not my type

Print a message that shows the type of the `age` variable

In [13]:
print("The age variable is of type", type(age))

The age variable is of type <class 'int'>


### Functions

You've seen that many instructions in Python contain **parentheses** `()`. What do they mean?
They are used to use **functions**. Functions contain one or more line of code that is run each time that function is called. 

The functions we used so far are `print()` and `type()`. 

Later in one of these tutorials we will learn how to make our own function.

### Lists

Sometimes you need to store many things in the same box. **Lists** can do that!

In [14]:
colors = ['red', 'blue', 'green','yellow']
print(len(colors))
print(type(colors))

4
<class 'list'>


What if you just need one element of a list? You can access single slots of the list using the `list[number]` syntax. 

In [15]:
print(colors[1]) # why is not red? Because Python starts counting from zero!

blue



#### [exercise] Last but not least

Print only the last element of the list of colours **without using numbers explicitly**.

*Tip*: Use one of the functions in the previous cell, and remember that counting starts from 0 in Python!

## 2. Decisions, decisions: if statement and for loop

### If statement

An `if` statement checks a condition: if the condition is true, Python executes the block of code under it; if the condition is false, the program can execute a different block of code under an `else` statement.

In [16]:
# test if a number is greater then a threshold
number = 27
threshold = 100

if number < threshold:
  print(number, " is greater than ", threshold)
else:
  print(number, " is smaller than ", threshold)

print("\n Have a good day, bye!")

27  is greater than  100

 Have a good day, bye!


Did you see that? The statements below the if statement are *shifted* by some blank spaces. 

This structure is called **indentation** and is necessary so that Python understands when the `if` and `else` statements are over.

#### [exercise] ...Manners!
Try to move the goodbye message inside the `else` statement using the `Tab` key and try different numbers. What happens?

### For loop

Sometimes you need to do the same thing multiple times. Luckily, the `for` loop automatically repeats the same action throughout a list 


In [17]:
for color in colors:
    print(color)

red
blue
green
yellow


If you need to explicitly access the slot number in a for loop, you can use the `range` function!

In [18]:
for i in range(0, len(colors),1): # range needs the first number, the last one and the size of the step.
    print(colors[i])

red
blue
green
yellow


#### [exercise] Top 5

1. Create a list of your top 5 movies (or songs) and print them sequentially. E.g.: **"Movie nr 5 in my favourite list is Barbie"**
<br>*Tip*: Use `range` and a for loop to access specific positions in the list

2. Movie ranked 0 sounds weird -  Try to make the list a bit more readable, from 1 to 5
   
3. Everybody likes suspance! -  Print the list from worst to best (without changing the list!) <br> *Tip*: You can change the step in the `range` function to -1 to iterate backwards!

In [19]:
top5 = ["Infinity War", "Interstellar", "Her", "Barbie"]
for i in range(len(top5)):
  print("Movie nr", i, "of my favourite list is ", top5[i])

Movie nr 0 of my favourite list is  Infinity War
Movie nr 1 of my favourite list is  Interstellar
Movie nr 2 of my favourite list is  Her
Movie nr 3 of my favourite list is  Barbie


### [exercise] Max and Min

Use a combination of the for loop and the if construct to detect tha highest and lowest number in a given list.

## 3. Higher dimensions: introduction to numpy arrays


Arrays are special variables that are ideal to deal with complex data. To create and manipulate arrays, we will use the `numpy` library, that contains pre-defined functions and data types. Let's start by creating a simple array:

### One-dimensional arrays

In [20]:
import numpy as np # numpy is a library: contains functions and data types that are useful for scientific computing.
array = np.array([1,2,3])
print(array)

[1 2 3]


In [21]:
print(array.shape, array.size, array.dtype)

(3,) 3 int64


### Two-dimensional arrays (matrices)

In [22]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
print(matrix.shape, matrix.size, matrix.dtype)

(3, 3) 9 int64


Matrices do not have just one index, but two: One for rows, and one for columns!


In [24]:
print("First row:", matrix[0,:])
print("First column:", matrix[:,0])
print("First element of first row:", matrix[0][0])
print("Element in second row, third column:", matrix[1][2])


First row: [1 2 3]
First column: [1 4 7]
First element of first row: 1
Element in second row, third column: 6


#### Exercise
1. Create a matrix with 3 rows and 4 columns
2. Create a `for`loop that prints each row of the matrix<br>*Tip*:The total number of rows in the matrix can be accessed using `matrix.shape[0]`
3. Create a `for` loop that prints each column of the matrix
4. Create a nested loop (two `for` loops inside each other) that prints each element of the matrix

In [25]:
# print each row of the matrix using a for loop
for i in range(matrix.shape[0]):
  print("Row", i, ":", matrix[i,:])

# print each column of the matrix using a for loop
for i in range(matrix.shape[1]):
  print("Column", i, ":", matrix[:,i])

# print each element of the matrix using two nested for loop loops
for i in range(matrix.shape[0]):
  for j in range(matrix.shape[1]):
    print("Element in row", i, "and column", j, ":", matrix[i][j])

Row 0 : [1 2 3]
Row 1 : [4 5 6]
Row 2 : [7 8 9]
Column 0 : [1 4 7]
Column 1 : [2 5 8]
Column 2 : [3 6 9]
Element in row 0 and column 0 : 1
Element in row 0 and column 1 : 2
Element in row 0 and column 2 : 3
Element in row 1 and column 0 : 4
Element in row 1 and column 1 : 5
Element in row 1 and column 2 : 6
Element in row 2 and column 0 : 7
Element in row 2 and column 1 : 8
Element in row 2 and column 2 : 9


### Matrix operations


You can add and subtract arrays of the same size:

In [26]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 3], [0, 1]])

# Matrix Addition
C = A + B
print("Added Matrices:\n", C)

# Matrix Subtraction
D = A - B
print("Subtracted Matrices:\n", D)


Added Matrices:
 [[3 5]
 [3 5]]
Subtracted Matrices:
 [[-1 -1]
 [ 3  3]]


There's several ways to multiply matrices. For example, one can multiply each element of a matrix for the same number (called *scalar* in this context), or multiply two matrices of the same size element by element (Element-wise product, or *Hadamard* product)

In [27]:
# Scalar Multiplication
scalar = 3
E = scalar * A
print("Scalar Multiplied Matrix:\n", E)

# Element-wise Multiplication
C = A * B  # Using the '*' operator for element-wise multiplication
print("Element-wise multiplied Matrix C:\n", C)

Scalar Multiplied Matrix:
 [[ 3  6]
 [ 9 12]]
Element-wise multiplied Matrix C:
 [[2 6]
 [0 4]]


#### Exercise
1. Create a 5x5 matrix of random numbers using the `np.random.randn()` function
2. Create a mask matrix made of zeroes such that the zeros are placed in a 3x3 window in the middle<br>*Tip*: Start by creating a matrix made of ones using `np.ones()`, then use the slicing operations to set the middle cells to 0
1. Use the mask matrix to create a random matrix with "a hole" of zeroes in a 2x2 window in the middle.

In [28]:
# Step 1: Create a 5x5 matrix of random numbers using np.random.randn function
random_matrix = np.random.randn(5, 5)
print("Original Random Matrix:\n", random_matrix)

# Step 2: Create a mask matrix made of 1s and 0s such that the zeros are placed in a 3x3 window in the middle
mask_matrix = np.ones((5, 5))
mask_matrix[1:4, 1:4] = 0
print("Mask Matrix:\n", mask_matrix)

# Step 3: Use the mask matrix to create a random matrix with a "hole" of zeros in a 3x3 window in the middle
masked_random_matrix = random_matrix * mask_matrix
print("Random Matrix with a 3x3 Hole:\n", masked_random_matrix)


Original Random Matrix:
 [[-1.95246989  0.0326065   1.32834566 -0.44206252  1.16185131]
 [ 1.02744972  0.26852519 -0.67747748  0.09570559  0.79467472]
 [ 0.18489653 -0.23515484 -0.81130334  0.73007239  0.71790637]
 [ 1.55178065 -2.41500149  1.09872305  1.07417977 -0.82460693]
 [-0.4954551  -0.77225576 -1.90597749 -0.21381899  1.03704027]]
Mask Matrix:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
Random Matrix with a 3x3 Hole:
 [[-1.95246989  0.0326065   1.32834566 -0.44206252  1.16185131]
 [ 1.02744972  0.         -0.          0.          0.79467472]
 [ 0.18489653 -0.         -0.          0.          0.71790637]
 [ 1.55178065 -0.          0.          0.         -0.82460693]
 [-0.4954551  -0.77225576 -1.90597749 -0.21381899  1.03704027]]
